// <auto-generated />
using System;
using Matches.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matches.Infrastructure.Migrations
{
    [DbContext(typeof(MatchesDbContext))]
    [Migration("20230511073453_AddPlayers")]
    partial class AddPlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MatchPlayer", b =>
                {
                    b.Property<Guid>("HomeMatchesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomePlayersId")
                        .HasColumnType("uuid");

                    b.HasKey("HomeMatchesId", "HomePlayersId");

                    b.HasIndex("HomePlayersId");

                    b.ToTable("HomePlayersMatches", (string)null);
                });

            modelBuilder.Entity("MatchPlayer1", b =>
                {
                    b.Property<Guid>("AwayMatchesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwayPlayersId")
                        .HasColumnType("uuid");

                    b.HasKey("AwayMatchesId", "AwayPlayersId");

                    b.HasIndex("AwayPlayersId");

                    b.ToTable("AwayPlayersMatches", (string)null);
                });

            modelBuilder.Entity("Matches.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Matches.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ShirtNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Matches.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TeamWinnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Years")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6de7e6c5-d265-4cbe-b81b-12b42b5737fb"),
                            LeagueId = new Guid("6e64b1e4-d662-4c04-8d67-0db65ead9eb7"),
                            StartDate = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Years = "2022/2023"
                        });
                });

            modelBuilder.Entity("MatchPlayer", b =>
                {
                    b.HasOne("Matches.Domain.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("HomeMatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matches.Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("HomePlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MatchPlayer1", b =>
                {
                    b.HasOne("Matches.Domain.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("AwayMatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matches.Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("AwayPlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matches.Domain.Entities.Match", b =>
                {
                    b.HasOne("Matches.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });
#pragma warning restore 612, 618
        }
    }
}
